### ISSUE TITLE
Version 4.8 binaries

### ISSUE THREAD

**Issue by graphixillusion** [lhmouse/nano-win#11]
Hi there. The official website for downloading the prebuilt binaries is not update: last downloadable version is 4.6 while 4.8 is the latest one. Is there any eta for the new builds to show up? In the meantime i'm trying to build from the source by myself but i'm getting troubles. I followed the readme and installed everything: **MSYS2, mingw-w64-x86_64-toolchain (with everything) and base-devel**.  Then i download the zip source from release page, unzip it and follow the rest of the guide. When i'm in the **nano-4.8** dir and launch `./configure` i get the error `bash: ./configure: No such file or directory`. If i type `autoconfig` first then the `./configure` command works but with errors. Now i'm trying the **build_nano-win.sh** as suggested in the Overview section of the readme and it's still running right now, i will report if something fails during the building but that script is not present in the zip of the 4.8 version, so i need help to build the last version from source. Thank you!

**Comment by lhmouse** [comment]
I may have access to update it today or tommorrow.

Unlike many other projects, **GNU nano**'s repo does not contain generated **autotools** scripts. Therefore you have to generate the **configure** script yourself with `./autogen.sh`, which performs a few other operations such as updating the **gnulib** submodule etc.

**Comment by lhmouse** [comment]
`autoconf` is not enough for generating all scripts required (you have to invoke `aclocal`, `autoheader`, `autoconf` and `automake` in a specific order, and you have to have knowledge of their relationship as well as some implementation details). The suggested way to do this is `autoreconf -i`. It should work well for most **autotools**-based projects, but not for **GNU nano** which has a _Git submodule_ that has to be updated before the process.

**Comment by graphixillusion** [comment]
I see, so i will wait for the compiled binaries. Thank you for explanation

**Comment by lhmouse** [comment]
Update now <https://files.lhmouse.com/nano-win/nano-win_8544_v4.8-4-g93fe54c6.7z>.
