### ISSUE TITLE
PowerShell sometimes crashes when starting nano

### ISSUE THREAD

**Issue by slugrustle** [lhmouse/nano-win#16]
I "installed" nano-win_9232_v5.2-4-ge724fdcb on Windows 10 Pro 19041.572 by unzipping it, copying the nano-win_9232_v5.2-4-ge724fdcb directory to C:\Program Files\, removing the i686-w64-mingw32 subdirectory (keeping x86_64-w64-mingw32), and adding C:\Users\user\Downloads\nano-win_9232_v5.2-4-ge724fdcb\x86_64-w64-mingw32\bin to the system Path environment variable.

If I run "nano.exe" or "nano" from powershell 5.1.19041.546 in my user (non-admin account) home directory, sometimes nano runs just fine, and sometimes PowerShell crashes before I can see the nano "screen" come up. Try repeatedly running nano and exiting to reproduce the issue. If it helps any, I typically run PowerShell maximized on a 1920x1080 monitor.

I do not experience the same issue when running nano from the Command Prompt.

**Comment by slugrustle** [comment]
Aha, it turns out that a nano.exe claiming to be nano version 2.7.5 was in C:\Windows\System32. Once I removed that executable, this problem went away. It must have been two executables with the same name in different places in the Path causing trouble.

**Comment by lhmouse** [comment]
Looks like there was a bug in your 2.7.5. nano is statically linked against 3rd-party libraries and should not suffer from such problems.
