### ISSUE TITLE
Update to nano 5.4?

### ISSUE THREAD

**Issue by Gavin-Holt** [lhmouse/nano-win#18]
Hi,

Would you consider a new binary release update to nano 5.4 "Terre des hommes" (2020 December 2 ) the benefits over 5.2 include:

"set stateflags: makes nano show the state of auto-indenting,
the mark, hard-wrapping, macro recording, and soft-wrapping in the
title bar. The flags take the place of "Modified", and a modified
buffer is instead indicated by an asterisk (*) after its name."

"set scrollercolor: the color of the indicator can be changed."

"Moving the cursor now skips over combining characters (and
other zero-width characters). Deleting a character deletes
also any succeeding zero-width characters, but backspacing
deletes just one character at a time"

Kind Regards Gavin Holt 

PS I have been playing with nano 5.3 as distributed in Git for Windows 64[1] and this has worked around the sys.fork() problem. Executing and piping works and is useful. However, 272MB is a big price to pay :)
 
[1] https://sourceforge.net/projects/git-for-windows.mirror/files/v2.29.2.windows.2/PortableGit-2.29.2.2-64-bit.7z.exe/download

**Comment by lhmouse** [comment]
Done.  <https://files.lhmouse.com/nano-win/nano-win_9371_v5.4-9-g7010a68f.7z>

**Comment by Gavin-Holt** [comment]
Many thanks
Kind Regards
