### ISSUE TITLE
Error expanding @PKGDATADIR@

### ISSUE THREAD

**Issue by rashil2000** [lhmouse/nano-win#24]
Hi, 

I uncommented the following line in my .nanorc

```
include "@PKGDATADIR@/*.nanorc"
```

but nano gives the error

```
Error in C:\Users\RashilGandhi/.nanorc on line 237: Error expanding @PKGDATADIR@/*.nanorc: No such file or directory
```

**Comment by lhmouse** [comment]
Please replace `@PKGDATADIR@` with an absolute path on your machine.

**Comment by rashil2000** [comment]
I was under the impression that nano automatically detects that.

Thanks!
