### ISSUE TITLE
Support italics 

### ISSUE THREAD

**Issue by rashil2000** [lhmouse/nano-win#25]
Nano has had italic and bold support since 5.0. But when specifying italic in any syntax highlighting file, the text doesn't become italic.

Surprisingly, MSys2's nano doesn't have this problem.

**Comment by lhmouse** [comment]
Windows console does not support italic types. Only the MSYS2 terminal (mintty) has this capability.

**Comment by rashil2000** [comment]
I know that. However, the ability to output italic text is independent of the terminal. Besides, the new Windows Terminal has italic support.

I tested both nano-win and Msys2-nano on all terminals (Windows Console, Windows Terminal, mintty etc.). Only Msys2-nano outputs italic characters in all terminals, and nano-win doesn't, in any terminal.

**Comment by lhmouse** [comment]
Maybe that's a limitation in the bundled curses library. GNU nano manipulates display via a curses library and here it is **ncurses 6.1**. I know no details about it but upgrading is of course worth trying. Will do later.

**Comment by rashil2000** [comment]
Sure, thanks for trying!

**Comment by lhmouse** [comment]
Note MSYS2 nano uses the MSYS2 ncurses, which is different from a native one. They use different approaches (console drivers) to operate consoles, so (native) **nano-win** will not work properly in **mintty**. 

I have uploaded a new build, but I personally do not use Windows Terminal. This editor is maintained mostly for occasional command-line editing tasks. Please test it yourself.

**Comment by rashil2000** [comment]
This build also doesn't show italics.

> Note MSYS2 nano uses the MSYS2 ncurses, which is different from a native one.

Maybe this is the reason. It might be that mingw's ncurses doesn't have italic support yet.

**Comment by lhmouse** [comment]
yeah that one requires msys-2.0.dll to be functional, which is a couple of MiBs larger but is of course much more versatile.

**Comment by rashil2000** [comment]
Hmm, looks like this is out of scope for this project then. Should I close this issue then?

**Comment by lhmouse** [comment]
yes this is likely WONTFIX.
