### ISSUE TITLE
Recommended Installation

### ISSUE THREAD

**Issue by eggplants** [lhmouse/nano-win#27]
Please tell me how to install... I would like to enable `.nanorc` and execute `nano.exe` in posh terminal like `nano sth.txt`.

**Comment by lhmouse** [comment]
There is no 'recommended' way of installation.

Personally I think it is not bad if you unpack everything into your `system32` directory, but it looks like kind of incitement, so i wouldn't do that.

**Comment by eabase** [comment]
Definitely still need some installation instructions, that is known to work for Window 10. Too many weird issues, and one need a known good start.

**Comment by eggplants** [comment]
The owner of this repository is not interested in providing a "standard" installation method for people who want to use `nano-win` easily, so please share your recommendations.
But I think such method will not be listed in README or INSTALL, even if you submit PR...

**Comment by eggplants** [comment]
My configuration:
https://gist.github.com/eggplants/d8ab847ddc5c433d5a09cba5d009b93f

**Comment by eabase** [comment]
@eggplants 
Thnaks, but it is looking as you're using WSL. I am **not** using WSL, and trying to get this to work in Powershell.

**Comment by eggplants** [comment]
@eabase fixed.
