### ISSUE TITLE
Is there any binary version provided for Windows?

### ISSUE THREAD

**Issue by duytrung** [lhmouse/nano-win#3]
Hi,

I found an older version of this editor available for download in sourceforge. 
I would like to request the repository maintainer to provide the binary version of the editor for new version.

Thank you.

Kind regards

TTn

**Comment by lhmouse** [comment]
At the moment, no. But if you (as well as others) want binary files, I may upload them for you.

The script `build-nano-win.sh` needs some fix-ups for i686. Please be patient.

**Comment by lhmouse** [comment]
See <https://github.com/lhmouse/nano-win/releases/tag/snapshot_2017-09-01>.

**Comment by lhmouse** [comment]
Updated URL:  <https://files.lhmouse.com/nano-win/>

This is also available beneath the title on the front page of this project.
