### ISSUE TITLE
Display collapses when the window is resized

### ISSUE THREAD

**Issue by eggplants** [lhmouse/nano-win#31]
On windows terminal, display collapses when the window is resized.
(`wsl nano` works well even if I resize.)

- half window

![image](https://user-images.githubusercontent.com/42153744/131451905-e2ed08de-0cd3-4fd1-8368-a12127badc7d.png)

- resize into full (win + arrow up)

![image](https://user-images.githubusercontent.com/42153744/131451986-a298616e-b1da-4559-86bf-53119862ef53.png)

- then resize into half window

![image](https://user-images.githubusercontent.com/42153744/131452148-a6ae41d2-bd49-43d7-9166-73ade4ae8d70.png)

**Comment by lhmouse** [comment]
On LInux and WSL, nano responds to the `SIGWINCH` signal which is delivered upon window resize events. I have disabled it because this signal is not supported by native applications, but if you happens to know how this is handled by ncurses, please let me know.
