### ISSUE TITLE
Enhancement: Use same profile location for Admin as for user

### ISSUE THREAD

**Issue by eabase** [lhmouse/nano-win#36]
99% of all PC users are only using 1 account (not counting `sudo`, or `Administrator`) accounts, while often mixing privilege escalated shells. Therefore it make no sense to have nano blindly (without telling user) that it is trying to load the `.nanorc` from a completely different location. 

```powershell
Enhancements	
    + .nanorc is loaded from "%USERPROFILE%\.nanorc" with normal privilege
      and from "%ALLUSERSPROFILE%\.nanorc" with elevated privilege.
    + Systemwide nanorc is loaded from "%ALLUSERSPROFILE%\nanorc".

ALLUSERSPROFILE   C:\ProgramData
USERPROFILE       C:\Users\<username>
```

**Comment by eabase** [comment]
Same should be said for the `filepos_history` as reported in #37 .

**Comment by lhmouse** [comment]
Loading distinct profiles is conventional for nano, as it allows different color schemes of titlebar, statusbar, etc. If you start nano via sudo on Linux you get the same behavior.

**Comment by eabase** [comment]
Yes, I know, but that is not very user friendly. 
Would have preferred a method to link one to the other.

This seem to work:

To create symbolic links of the _Administrator_ user's `filepos_history` and **`.nanorc`** to the *real* <username> ones,  
do the following (from an elevated shell):

```powershell
New-Item -ItemType SymbolicLink -Path "C:\ProgramData\.local\share\nano\filepos_history" -Target  "C:\Users\<username>\.local\share\nano\filepos_history" -Force
New-Item -ItemType SymbolicLink -Path "C:\ProgramData\.nanorc" -Target  "C:\Users\<username>\.nanorc" -Force
```

Closing issue for now.

**Comment by eabase** [comment]
Thanks, but I avoid the CMD like the COVID plague.

**Comment by lhmouse** [comment]
I don't like Windows either, but it is not a legitimate reason to break up with it.
