### ISSUE TITLE
FAQ: Where is the "positionlog" file located?

### ISSUE THREAD

**Issue by eabase** [lhmouse/nano-win#37]
Would be great to know where the file cursor position file is located as enabled by the `set positionlog` flag.

Also, what is the following location doing? 

`-o <dir>       --operatingdir=<dir>    Set operating directory`

**Comment by eabase** [comment]
Ok,, I found the first under `C:\ProgramData` in:  
`C:\ProgramData\.local\share\nano\filepos_history`

**Comment by eabase** [comment]
A workaround could be to symlink the Administrator created file to the Users file, but then all permissions have to be allowed.

**Comment by eabase** [comment]
Solved by symbolic link, see #36

**Comment by garoto** [comment]
All your "issue bumping" is highly annoying. Just pick a topic and stick to it till you get closure.
