### ISSUE TITLE
Windows path convention does not work

### ISSUE THREAD

**Issue by eabase** [lhmouse/nano-win#38]
Rather how not to install on Windows-10. 

The number one most important thing to notice, is that the file paths given in the `include` statements, in the **`.nanorc`** **HAVE** to be in the POSIX format. I.e. not using the windows back-slash convention. Therefore you must write it like this:

```python
include "C:\mybin\nano\nanorc\*.nanorc"     # Windows paths does NOT work!
include "/mybin/nano/nanorc/*.nanorc"       # This works!
```

At this point I have no idea if this is a bug or new development. But it surely would have helped to have known this in advance, before spending hours trying to figure out why something that used to be *obvious* doesn't work. 

@lhmouse  
Please make this clear in your README.

**Comment by lhmouse** [comment]
The `glob()` function from GNU lib doesn't recognize backslashes in paths. Please file a PR if you think it is necessary.
