### ISSUE TITLE
GPL-3.0 license

### ISSUE THREAD

**Issue by NewbProgrammer101** [lhmouse/nano-win#4]
Unlike LGPL, the GPL prohibits proprietary use. Windows is proprietary.

Why bother making a port to windows when the license prohibits you to do so.

**Comment by lhmouse** [comment]
[Your argument is nonsense](https://www.gnu.org/licenses/gpl-faq.html#SystemLibraryException). In addition to that, I am not interested in your advocacy of freedom/open sourcing/GPl/whatsoever and please take the war elsewhere.
