### ISSUE TITLE
nano not working on Win11

### ISSUE THREAD

**Issue by kaboddy** [lhmouse/nano-win#41]
Seems after an update to the version, nano doesn't launch anymore?  I've got the issue on 2 PCs - Both popup 'The code execution cannot proceed because libmcfgthread-1.dll was not found'.  Reinstall didn't help.

**Comment by lhmouse** [comment]
Apologies for the trouble. I have uploaded a new build. Please refer to #40 for details.

**Comment by lhmouse** [comment]
Apologies for the trouble. I have uploaded a new build. Please refer to #40 for details.

**Comment by kaboddy** [comment]
Wow.  That worked today!  Thanks!
