### ISSUE TITLE
Version 2.9.2 Released!

### ISSUE THREAD

**Issue by duytrung** [lhmouse/nano-win#5]
Hi,

Version 2.9.2 release, please update the binary version. Thank you!

**Comment by lhmouse** [comment]
Updated as <https://files.lhmouse.com/nano-win/nano-win_v2.9.2-4-gd8155168.7z>.

This update includes some cleanup. Vim-style locking files are now enabled. UTF-8 support is now removed because of the fact that it hasn't worked after all.

**Comment by lhmouse** [comment]
Please close this issue after testing the new package.
