### ISSUE TITLE
How to use all the nanorc files packed in the release build?

### ISSUE THREAD

**Issue by kasper3** [lhmouse/nano-win#7]
Is there a way that I can reference all files under `share\nano` directory in `%HOME%\.nanorc` file, so where ever I will place `nano.exe` after that, it will all the syntax highlighting settings?

**Comment by lhmouse** [comment]
I am afraid this is not possible.

The path to all `.nanorc` files is absolute. On Linux for example the path is virtually relative to the root mount point so it should look like `/usr/local/share/nano/*.nanorc`.

I haven't tried relative paths but I don't think they will work reliably. You may want to put those `.nanorc` files in `C:\Windows\nanorc` or `C:\Program Files\nanorc` then reference them as follows:

```
include "C:/Windows/nanorc/*.nanorc"
```

**Comment by kasper3** [comment]
Thanks, I copied the `share\nano` directory at `C:\Users\Kasper\nanorc` and created a file `C:\Users\Kasper\.nanorc` with the following line:

```ini
include "C:/Users/Kasper/nanorc/*.nanorc"
```

and syntax highlighting worked!

No highlighting for `.bat` or `.cmd` or `ps1` files though. 😢

**Comment by lhmouse** [comment]
> No highlighting for .bat or .cmd or ps1 files though. :cry:

Feel free to contribute. :>
